name: Dev.to Publisher

on:
  push:
    branches:
      - "**"
    paths:
      - "articles/**/*.md"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Identify changed markdown files
        id: changed_files
        run: |
          # Fetch the list of changed markdown files
          git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" -- "articles/**/*.md" > changed_files.txt
          
          # Create a comma-separated list of files
          files=$(tr '\n' ',' < changed_files.txt | sed 's/,$//')
          echo "changed_files=$files" >> $GITHUB_ENV

      - name: Set dry-run mode based on branch
        id: dry_run_check
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "dry_run=false" >> $GITHUB_ENV
          else
            echo "dry_run=true" >> $GITHUB_ENV
          fi

      - name: Publish changed markdown articles to Dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.changed_files }}
          branch: ${{ env.CURRENT_BRANCH }}
          conventional_commits: true
          dry_run: ${{ env.dry_run }}
