name: Identify Changed Files

on:
  push:
    branches:
      - main

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Fetch all history for accurate comparisons
        run: git fetch --unshallow

      - name: Determine Changed Files
        id: changed_files
        run: |
          # Get the previous commit before the merge
          PREVIOUS_COMMIT=$(git rev-parse HEAD^1)
          echo "Previous commit: $PREVIOUS_COMMIT"

          # List files changed in the merge commit
          git diff --name-only "$PREVIOUS_COMMIT" HEAD > changed_files.txt

          # Print changed files for debugging
          cat changed_files.txt

          # Save the list of changed files as an environment variable
          CHANGED_FILES=$(paste -sd, changed_files.txt)
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Show Changed Files
        run: echo "Changed files: ${{ env.changed_files }}"
