name: Identify Changed Files

on:
  push:
    branches:
      - main

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Fetch all history (if needed)
        run: |
          git fetch --all

      - name: Determine Changed Files
        id: changed_files
        run: |
          # Ensure we have access to the previous commit
          PREVIOUS_COMMIT=$(git rev-list --parents -n 1 HEAD | awk '{print $2}')
          echo "Previous commit: $PREVIOUS_COMMIT"

          # List files changed in the merge commit
          git diff --name-only "$PREVIOUS_COMMIT" HEAD > changed_files.txt

          # Print changed files for debugging
          cat changed_files.txt

          # Save the list of changed files as an environment variable
          CHANGED_FILES=$(paste -sd, changed_files.txt)
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Show Changed Files
        run: |
          echo "Changed files: ${{ env.changed_files }}"
