name: markdown-lint

on:
  push:
    branches:
      - "**"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: npm install -g markdownlint-cli@0.41.0

      - name: Run markdownlint
        env:
          CONFIG: |
            {
              "comment": "Default rules",
              "default": true,
              "whitespace": false,
              "line_length": false,
              "ul-start-left": false,
              "ul-indent": false,
              "no-inline-html": false,
              "no-bare-urls": false,
              "fenced-code-language": false,
              "first-line-h1": false,
              "no-duplicate-header": false,
              "no-emphasis-as-header": false,
              "single-h1": false
            }
        run: |
          CONFIG_FILE="$(mktemp)"
          echo "$CONFIG" > "$CONFIG_FILE"
          markdownlint '**/*.md' --ignore node_modules -c "$CONFIG_FILE"
