  name: Mastodon Publisher

  on:
    push:
      branches:
        - "**"

  jobs:
    publish:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Mastodon Post on GitHub Actions
          id: mastodon_toot
          uses: cbrgm/mastodon-github-action@v2
          with:
            access-token: ${{ secrets.MASTODON_TOKEN }}
            url: 'https://mastodon.social'
            message: "Hello from GitHub Actions!"

        # Example on how to use outputs from the Mastodon action step.
        - name: Get toot information
          run: |
            echo "Toot ID: ${{ steps.mastodon_toot.outputs.id }}"
            echo "Toot URL: ${{ steps.mastodon_toot.outputs.url }}"
            echo "Scheduled at: ${{ steps.mastodon_toot.outputs.scheduled_at }}"

        - name: Publish article and get URL
          run: |
            response=$(curl -X POST "https://dev.to/api/articles" \
                      -H "Content-Type: application/json" \
                      -H "api-key: ${{ secrets.DEVTO_TOKEN }}" \
                      -d '{
                            "article": {
                              "title": "test",
                              "body_markdown": "test",
                              "published": true
                            }
                          }')
            ARTICLE_URL=$(echo $response | jq -r '.article.url')
            echo $response
            echo "url=${ARTICLE_URL}" >> $GITHUB_OUTPUT

        - name: Output article URL
          run: |
            echo "The article is published at: ${{ steps.publish-article.outputs.url }}"
